# Repository settings for @juspay/shelly
# This file is used by the Settings GitHub App to manage repository configuration

repository:
  # Repository basic settings
  name: shelly
  description: 'AI-powered development assistant combining error analysis, repository organization, and Memory Bank for enhanced AI-assisted development workflows'
  homepage: https://juspay.github.io/shelly/
  topics:
    - javascript
    - nodejs
    - cli
    - ai-powered
    - error-analysis
    - repository-organization
    - memory-bank
    - development-assistant
    - shell-integration
    - ai-assisted-development
    - command-line-tools
    - developer-productivity
    - project-scaffolding
    - github-integration
    - documentation-generation

  # Repository features
  private: false
  has_issues: true
  has_projects: true
  has_wiki: false
  has_pages: true
  has_downloads: true
  default_branch: release

  # Repository settings
  allow_squash_merge: true
  allow_merge_commit: false
  allow_rebase_merge: false
  allow_auto_merge: true
  delete_branch_on_merge: true
  enable_automated_security_fixes: true
  enable_vulnerability_alerts: true

# Labels configuration
labels:
  # Standard issue types
  - name: bug
    color: d73a4a
    description: Something isn't working

  - name: documentation
    color: 0075ca
    description: Improvements or additions to documentation

  - name: duplicate
    color: cfd3d7
    description: This issue or pull request already exists

  - name: enhancement
    color: a2eeef
    description: New feature or request

  - name: good first issue
    color: 7057ff
    description: Good for newcomers

  - name: help wanted
    color: 008672
    description: Extra attention is needed

  - name: invalid
    color: e4e669
    description: This doesn't seem right

  - name: question
    color: d876e3
    description: Further information is requested

  - name: wontfix
    color: ffffff
    description: This will not be worked on

  # Shelly feature area labels
  - name: error-analysis
    color: ff6b6b
    description: Issues related to command error analysis and AI suggestions

  - name: repository-organization
    color: 4ecdc4
    description: Issues related to project scaffolding and GitHub integration

  - name: memory-bank
    color: 45b7d1
    description: Issues related to AI context management and documentation

  - name: ai-integration
    color: 96ceb4
    description: Issues related to AI services and content generation

  - name: shell-integration
    color: feca57
    description: Issues related to bash, zsh, tcsh shell compatibility

  - name: cli-interface
    color: ff9ff3
    description: Issues related to command-line interface and user experience

  # Technical labels
  - name: dependencies
    color: 0366d6
    description: Pull requests that update a dependency file

  - name: security
    color: ee0701
    description: Security related issues

  - name: performance
    color: fbca04
    description: Performance related improvements

  - name: cross-platform
    color: 54a0ff
    description: Issues related to macOS, Linux, Windows compatibility

  - name: testing
    color: 5f27cd
    description: Issues related to testing and quality assurance

  # Process labels
  - name: automated
    color: 00d2d3
    description: Automated pull requests from bots

  - name: github-actions
    color: 2f3542
    description: Issues related to CI/CD workflows

  - name: docker
    color: 0984e3
    description: Issues related to Docker integration

# Branch protection rules
branches:
  - name: release
    protection:
      required_status_checks:
        strict: true
        contexts:
          - 'Shelly CI/CD Pipeline / Code Quality & Linting (Node.js 18.x)'
          - 'Shelly CI/CD Pipeline / Code Quality & Linting (Node.js 20.x)'
          - 'Shelly CI/CD Pipeline / Functional Testing (ubuntu-latest, 18.x, bash)'
          - 'Shelly CI/CD Pipeline / Functional Testing (ubuntu-latest, 20.x, bash)'
          - 'Shelly CI/CD Pipeline / Security Audit'
          - 'Shelly CI/CD Pipeline / Documentation Validation'
          - 'Dependency Review / dependency-review'
      enforce_admins: true
      required_pull_request_reviews:
        required_approving_review_count: 2
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
        dismissal_restrictions: {}
      restrictions: null
      required_linear_history: true
      allow_force_pushes: false
      allow_deletions: false

# Teams configuration
teams:
  - name: 'shelly-maintainers'
    permission: admin
  - name: 'shelly-core-team'
    permission: write
  - name: 'shelly-organize-team'
    permission: write
  - name: 'shelly-memory-team'
    permission: write
  - name: 'shelly-ai-team'
    permission: write
  - name: 'shelly-cli-team'
    permission: write
  - name: 'shelly-shell-team'
    permission: write
  - name: 'shelly-contributors'
    permission: write
  - name: 'docs-team'
    permission: write
  - name: 'devops-team'
    permission: write
  - name: 'community-team'
    permission: write
  - name: 'product-team'
    permission: triage

# Collaborators (optional)
collaborators: []

# Milestones
milestones:
  - title: v1.0.0
    description: First stable release
    state: open
  - title: v1.1.0
    description: Minor feature updates
    state: open
